[package]
name = "task2"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.19"
eframe = "0.19"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rfd = "0.11"  # 如果你使用 rfd 库
regex = "1.5"